module.exports = {
  future: {
    // removeDeprecatedGapUtilities: true,
    // purgeLayersByDefault: true,
  },
  purge: [],
  theme: {
    colors: {
      black: {
        default: "var(--colorBlack)",
        l1: "var(--colorBlackLighten1)",
        l2: "var(--colorBlackLighten2)",
        l3: "var(--colorBlackLighten3)",
        l4: "var(--colorBlackLighten4)",
        d1: "var(--colorBlackDarken1)",
        d2: "var(--colorBlackDarken2)",
        d3: "var(--colorBlackDarken3)",
        d4: "var(--colorBlackDarken4)",
      },
      white: {
        default: "var(--colorWhite)",
        l1: "var(--colorWhiteLighten1)",
        l2: "var(--colorWhiteLighten2)",
        l3: "var(--colorWhiteLighten3)",
        l4: "var(--colorWhiteLighten4)",
        d1: "var(--colorWhiteDarken1)",
        d2: "var(--colorWhiteDarken2)",
        d3: "var(--colorWhiteDarken3)",
        d4: "var(--colorWhiteDarken4)",
      },
      gray: {
        default: "var(--colorGray)",
        l1: "var(--colorGrayLighten1)",
        l2: "var(--colorGrayLighten2)",
        l3: "var(--colorGrayLighten3)",
        l4: "var(--colorGrayLighten4)",
        d1: "var(--colorGrayDarken1)",
        d2: "var(--colorGrayDarken2)",
        d3: "var(--colorGrayDarken3)",
        d4: "var(--colorGrayDarken4)",
      },
      primary: {
        default: "var(--colorPrimary)",
        l1: "var(--colorPrimaryLighten1)",
        l2: "var(--colorPrimaryLighten2)",
        l3: "var(--colorPrimaryLighten3)",
        l4: "var(--colorPrimaryLighten4)",
        d1: "var(--colorPrimaryDarken1)",
        d2: "var(--colorPrimaryDarken2)",
        d3: "var(--colorPrimaryDarken3)",
        d4: "var(--colorPrimaryDarken4)",
      },
      secondary: {
        default: "var(--colorSecondary)",
        l1: "var(--colorSecondaryLighten1)",
        l2: "var(--colorSecondaryLighten2)",
        l3: "var(--colorSecondaryLighten3)",
        l4: "var(--colorSecondaryLighten4)",
        d1: "var(--colorSecondaryDarken1)",
        d2: "var(--colorSecondaryDarken2)",
        d3: "var(--colorSecondaryDarken3)",
        d4: "var(--colorSecondaryDarken4)",
      },
      tertiary: {
        default: "var(--colorTertiary)",
        l1: "var(--colorTertiaryLighten1)",
        l2: "var(--colorTertiaryLighten2)",
        l3: "var(--colorTertiaryLighten3)",
        l4: "var(--colorTertiaryLighten4)",
        d1: "var(--colorTertiaryDarken1)",
        d2: "var(--colorTertiaryDarken2)",
        d3: "var(--colorTertiaryDarken3)",
        d4: "var(--colorTertiaryDarken4)",
      },
      quaternary: {
        default: "var(--colorQuaternary)",
        l1: "var(--colorQuaternaryLighten1)",
        l2: "var(--colorQuaternaryLighten2)",
        l3: "var(--colorQuaternaryLighten3)",
        l4: "var(--colorQuaternaryLighten4)",
        d1: "var(--colorQuaternaryDarken1)",
        d2: "var(--colorQuaternaryDarken2)",
        d3: "var(--colorQuaternaryDarken3)",
        d4: "var(--colorQuaternaryDarken4)",
      },
      critical: {
        default: "var(--statusDarkCritical)",
        light: "var(--statusLightCritical)",
        l1: "var(--colorCriticalLighten1)",
        l2: "var(--colorCriticalLighten2)",
        l3: "var(--colorCriticalLighten3)",
        l4: "var(--colorCriticalLighten4)",
        d1: "var(--colorCriticalDarken1)",
        d2: "var(--colorCriticalDarken2)",
        d3: "var(--colorCriticalDarken3)",
        d4: "var(--colorCriticalDarken4)",
      },
      serious: {
        default: "var(--statusDarkSerious)",
        light: "var(--statusLightSerious)",
        l1: "var(--colorSeriousLighten1)",
        l2: "var(--colorSeriousLighten2)",
        l3: "var(--colorSeriousLighten3)",
        l4: "var(--colorSeriousLighten4)",
        d1: "var(--colorSeriousDarken1)",
        d2: "var(--colorSeriousDarken2)",
        d3: "var(--colorSeriousDarken3)",
        d4: "var(--colorSeriousDarken4)",
      },
      caution: {
        default: "var(--statusDarkCaution)",
        light: "var(--statusLightCaution)",
        l1: "var(--colorCautionLighten1)",
        l2: "var(--colorCautionLighten2)",
        l3: "var(--colorCautionLighten3)",
        l4: "var(--colorCautionLighten4)",
        d1: "var(--colorCautionDarken1)",
        d2: "var(--colorCautionDarken2)",
        d3: "var(--colorCautionDarken3)",
        d4: "var(--colorCautionDarken4)",
      },
      normal: {
        default: "var(--statusDarkNormal)",
        light: "var(--statusLightNormal)",
        l1: "var(--colorNormalLighten1)",
        l2: "var(--colorNormalLighten2)",
        l3: "var(--colorNormalLighten3)",
        l4: "var(--colorNormalLighten4)",
        d1: "var(--colorNormalDarken1)",
        d2: "var(--colorNormalDarken2)",
        d3: "var(--colorNormalDarken3)",
        d4: "var(--colorNormalDarken4)",
      },
      standby: {
        default: "var(--statusDarkStandby)",
        light: "var(--statusLightStandby)",
        l1: "var(--colorStandbyLighten1)",
        l2: "var(--colorStandbyLighten2)",
        l3: "var(--colorStandbyLighten3)",
        l4: "var(--colorStandbyLighten4)",
        d1: "var(--colorStandbyDarken1)",
        d2: "var(--colorStandbyDarken2)",
        d3: "var(--colorStandbyDarken3)",
        d4: "var(--colorStandbyDarken4)",
      },
      off: {
        default: "var(--statusDarkOff)",
        light: "var(--statusLightOff)",
        l1: "var(--colorOffLighten1)",
        l2: "var(--colorOffLighten2)",
        l3: "var(--colorOffLighten3)",
        l4: "var(--colorOffLighten4)",
        d1: "var(--colorOffDarken1)",
        d2: "var(--colorOffDarken2)",
        d3: "var(--colorOffDarken3)",
        d4: "var(--colorOffDarken4)",
      },
      tag1: {
        default: "var(--colorTag1)",
        l1: "var(--colorTag1Lighten1)",
        l2: "var(--colorTag1Lighten2)",
        l3: "var(--colorTag1Lighten3)",
        l4: "var(--colorTag1Lighten4)",
        d1: "var(--colorTag1Darken1)",
        d2: "var(--colorTag1Darken2)",
        d3: "var(--colorTag1Darken3)",
        d4: "var(--colorTag1Darken4)",
      },
      tag2: {
        default: "var(--colorTag2)",
        l1: "var(--colorTag2Lighten1)",
        l2: "var(--colorTag2Lighten2)",
        l3: "var(--colorTag2Lighten3)",
        l4: "var(--colorTag2Lighten4)",
        d1: "var(--colorTag2Darken1)",
        d2: "var(--colorTag2Darken2)",
        d3: "var(--colorTag2Darken3)",
        d4: "var(--colorTag2Darken4)",
      },
      tag3: {
        default: "var(--colorTag3)",
        l1: "var(--colorTag3Lighten1)",
        l2: "var(--colorTag3Lighten2)",
        l3: "var(--colorTag3Lighten3)",
        l4: "var(--colorTag3Lighten4)",
        d1: "var(--colorTag3Darken1)",
        d2: "var(--colorTag3Darken2)",
        d3: "var(--colorTag3Darken3)",
        d4: "var(--colorTag3Darken4)",
      },
      tag4: {
        default: "var(--colorTag4)",
        l1: "var(--colorTag4Lighten1)",
        l2: "var(--colorTag4Lighten2)",
        l3: "var(--colorTag4Lighten3)",
        l4: "var(--colorTag4Lighten4)",
        d1: "var(--colorTag4Darken1)",
        d2: "var(--colorTag4Darken2)",
        d3: "var(--colorTag4Darken3)",
        d4: "var(--colorTag4Darken4)",
      },
    }
  },
  variants: {},
  plugins: [],
}
